In [5]:
import pandas as pd
import re

In [6]:
character_df = pd.read_csv("characters.csv")
character_df

,book,character
0,Category:Catching Fire characters,Haymitch Abernathy
1,Category:Catching Fire characters,Atala
2,Category:Catching Fire characters,Beetee Latier
3,Category:Catching Fire characters,Blight
4,Category:Catching Fire characters,Bonnie
...,...,...
171,Category:The Hunger Games characters,Category:Tributes in the 74th Hunger Games
172,Category:The Hunger Games characters,Effie Trinket
173,Category:The Hunger Games characters,Madge Undersee
174,Category:The Hunger Games characters,Mayor Undersee
175,Category:The Hunger Games characters,Venia

In [8]:
# Remove brackets and text within brackets
character_df['character'] = character_df['character'].apply(lambda x: re.sub("[\(].*?[\)]", "", x)) 
character_df['character_firstname'] = character_df['character'].apply(lambda x: x.split(' ', 1)[0])
character_df

,book,character,character_firstname
0,Category:Catching Fire characters,Haymitch Abernathy,Haymitch
1,Category:Catching Fire characters,Atala,Atala
2,Category:Catching Fire characters,Beetee Latier,Beetee
3,Category:Catching Fire characters,Blight,Blight
4,Category:Catching Fire characters,Bonnie,Bonnie
...,...,...,...
171,Category:The Hunger Games characters,Category:Tributes in the 74th Hunger Games,Category:Tributes
172,Category:The Hunger Games characters,Effie Trinket,Effie
173,Category:The Hunger Games characters,Madge Undersee,Madge
174,Category:The Hunger Games characters,Mayor Undersee,Mayor
175,Category:The Hunger Games characters,Venia,Venia

In [10]:
nickname_mapping = {
    'Primrose': 'Prim',
}

character_df['character_nickname'] = character_df['character_firstname'].map(nickname_mapping)

In [11]:
character_df.to_csv('characters_ref.csv', index=False)